### ISSUE TITLE
The image don't start at origin of the screen

### ISSUE THREAD

**Issue by titouan73** [Snille/MMM-Profilepicture#1]
Hello i'm sorry to disturb you but I use your module to setup a background image for each profile and for each one the background does not start at the botoom of the screen. Would it be possible to add an 'origin' parameter in order to specify where we want the bottom left corner of the image be. 

![image](https://user-images.githubusercontent.com/25641597/145772206-8f1ac137-37bc-4d1c-a750-9235bd132cc9.png)

**Comment by Snille** [comment]
Hi, I'm not sure what you mean? The module just displays a picture in the "area" you define (default it's fullscreen_below @ 100% both horizontally and vertically). You can simply make a picture in the form you want... :) If you want a "black" part of the picture at the bottom, just leave whatever height you want "black" in the actual picture...

**Comment by titouan73** [comment]
The picture is 1920x1080 so the screen. I didn't transform it via css. On top of that even with css I can't fill this black bar at the bottom

**Comment by Snille** [comment]
Hm... Try to disable all other modules and see if it's something else that "creates" the black bar... Have you "disabled" the margins in the CSS? By default the MM has margins set, you can change that in the costume.css... Here is all the "config" you need... Just tested it on my "dev" mirror. I have only enabled "MMM-Remote-Control", "MMM-Modulebar", "clock" and the "MMM-Profilepicture" (set to class "everyone" in this case. :)... You can see the margins in lower right file... 
![image](https://user-images.githubusercontent.com/1011699/145898956-db461526-1618-43e1-a73d-8a6ee038cc98.png)

**Comment by titouan73** [comment]
Thanks I will give it a try tomorrow 😉

**Comment by titouan73** [comment]
Ok the problem was due to the weird form factor of my raspi display. I've forced a pixed definition off the wallpaper and it overflow a bit but I don't care. Thanks for your help.
